### ISSUE TITLE
cef.redist.x64

### ISSUE THREAD

**Issue by Mr4g** [OutSystems/CefGlue#107]
I use cef.redist.x64 to 116.0.15 
Xilium.CefGlue.CefVersionMismatchException: 'CEF runtime version mismatch: loaded version API hash "1091d9b7f17abbbf86cbbf50db7106a2bad98ab5", but supported "95bf7fa1356070be95b7a6fee958355c6619fb63" (106.0.26+ge105400+chromium-106.0.5249.91).'

how i can fix it ?

**Comment by joaompneves** [comment]
You would need to upgrade CefGlue... that might not be that easy, it can take some effort and knowledge to do it by yourself, because some CEF upgrades might introduce breaking changes or require some rework. Unless you know what you're doing, you should stick with what we provide. 
Currently CefGlue uses CEF 106 and we have a PR opened to support CEF 112 (https://github.com/OutSystems/CefGlue/pull/89).

**Comment by Mr4g** [comment]
Can you tell me what packages I should use to make it work?

**Comment by joaompneves** [comment]
Using the code provided or the CefGlue nuget (https://www.nuget.org/packages/CefGlue.Avalonia) it should work without issues.
Either way the current version on main:
https://github.com/OutSystems/CefGlue/blob/main/Directory.Build.props#L6

**Comment by Mr4g** [comment]
https://github.com/Mr4g/ViMultiSync.git

can you check ? What package I have wrongly installed. As far as I can see they are all the latest and Avalonia too

**Comment by joaompneves** [comment]
well, you only need to reference either CefGlue.Avalonia... the others (https://github.com/Mr4g/ViMultiSync/blob/master/ViMultiLink%20Engage/ViMultiSync.csproj#L27-L34) are references implicitly. 
Also seems that you want to use the WebView which is not this project. The WebView is a CefGlue wrapper.
In that case just reference WebViewControl-Avalonia.
