### ISSUE TITLE
Relationship between Xilium.CefGlue and OutSystems.CefGlue

### ISSUE THREAD

**Issue by JacobMikkelsen** [OutSystems/CefGlue#134]
Since both Xilium.CefGlue and OutSystems.CefGlue appear to be actively maintained repositories with a common history, I'm curious if there's a stated difference between the two. What was Xilium not able to offer that lead to OutSystems forking, and what is Xilium trying to maintain that OutSystems does not? Having just scratched the surface of the repos, it seems like OutSystems is favouring newer technologies while Xilium is trying to maintain support for existing consumers.

My particular interest in this is because I've recently been tasked with uplifting an internal application using an old Xilium.CefGlue version. I'm wondering whether I should keep using Xilium (appealing with WinForms support and potentially easier .NET 4.5 targetting), or switch to OutSystems (though I would need to put in work to make it compatible with our application).

Sorry to drag you over here @dmitry-azaraev, but I'd be grateful for any input from the Xilium side of things too.

**Comment by joaompneves** [comment]
We forked Xilium.CefGlue, a few years ago, to introduce support for macOS (and eventually Linux). Since we were not able to come to an agreement with the Xilium.CefGlue's maintainer, we opted to follow our path, which is to provide a webview component that can run on Windows and macOS (using Avalonia), while Xilium only supports windows. We still rely on some of the work done on the CefGlue core parts in Xilium.CefGlue, but all the visual components we provide are completely different and have more and enhanced built-in functionalities (eg: JS evaluation support).
We also provide ready to use nuget packages for x64 and ARM64.

**Comment by dmitry-azaraev** [comment]
@JacobMikkelsen Xilium.CefGlue did not actively maintained nowadays. You might expect only minimal updates around 6 times per year (e.g. 6 CEF versions). It requires some love in form of big rewrite (which in past was started few times but never finished by various "real-life" reasons). It generally did not includes any samples or not provide any integration guide. It generally targets to CEF users who explicitly know what it want, used custom CEF builds with own API extensions, etc. I might back on board only if someone will want seriously contribute to new bindings, to solve fundamental flaws in current CefGlue's design.

In turn, this means feel free to use OutSystems version, it better supported and generally you will not be limited in anything.

**Comment by JacobMikkelsen** [comment]
Thank you @joaompneves and @dmitry-azaraev for your responses! They'll definitely help our decision on which way to head going forwards. Closing this issue.
